//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTRONGHUY_2210900029_K22CNTT1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danh_muc_xe_hoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danh_muc_xe_hoi()
        {
            this.chi_tiet_gio_hang = new HashSet<chi_tiet_gio_hang>();
        }
    
        public int ma_xe { get; set; }
        public string ten_xe { get; set; }
        public string hang_xe { get; set; }
        public Nullable<decimal> gia_ban { get; set; }
        public string mo_ta { get; set; }
        public Nullable<int> so_luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_gio_hang> chi_tiet_gio_hang { get; set; }
    }
}
