//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTRONGHUY_2210900029_K22CNTT1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOTRONGHUY_CNTT1_2210900029_Project2Entities : DbContext
    {
        public DOTRONGHUY_CNTT1_2210900029_Project2Entities()
            : base("name=DOTRONGHUY_CNTT1_2210900029_Project2Entities")
        {
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chi_tiet_gio_hang> chi_tiet_gio_hang { get; set; }
        public virtual DbSet<danh_muc_xe_hoi> danh_muc_xe_hoi { get; set; }
        public virtual DbSet<don_hang> don_hang { get; set; }
        public virtual DbSet<gio_hang> gio_hang { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<quan_tri> quan_tri { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<thanh_toan> thanh_toan { get; set; }
    }
}
