//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTRONGHUY_2210900029_K22CNTT1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quan_tri
    {
        public string tai_khoan { get; set; }
        public string mat_khau { get; set; }
        public Nullable<byte> trang_thai { get; set; }
    }
}
