//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTRONGHUY_2210900029_K22CNTT1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanh_toan
    {
        public int ma_thanh_toan { get; set; }
        public Nullable<int> ma_dh { get; set; }
        public Nullable<System.DateTime> ngay_thanh_toan { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public string phuong_thuc { get; set; }
        public Nullable<byte> trang_thai { get; set; }
        public string mo_ta { get; set; }
    
        public virtual don_hang don_hang { get; set; }
    }
}
